os: linux
sudo: required
dist: bionic
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - sudo add-apt-repository ppa:deadsnakes/ppa --yes
  - sudo apt-get --yes --force-yes install python3-venv
  - pip install ansible
  - pip install flake8
  - pip3 install ansible-doc-extractor
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - ansible --version
  - flake8 --version

env:
  global:
    secure: C1LJNb1qVzjyx9ZG0rbtn42eyb7Qrw7puHQ+ihLaNAV789iHO3h/wDw9maneR/p1L4bzRtiktdJ6pKqmhUQlSYVLl6YIVEsOfUAAFVg0O+mQQJcHNWpAgVtEuFFj2ahiNq9KHkQjdOHA8+uHBhmPX/kj5bvUArM7Wzr5ZmEjjU/I7oYBETfWYs4WKj/vpux23V/AzD6OpxiBdxDtPRqNxYyomJc8EhwdXyL+diOuPd1+CFFEKUKhGfPc5YjAJGaWiLHqXspNBu5nmWh9TNRyQQyNYNAo9EiGkpOAT5dlyxXj7D8aU/kyMryFPTrVVmk0IQI0/XN6zc+J/FErQ2eYiiskAlmLN0CEGFdklyDamuAOqrpNH8NHNuVraX6V2KiHoIKps0wwJBnl9I1khl1wY5tHLL2bAT1o3wHRPN3xbRxlYxis+0WIEOVWlBNYvz3KRYevu11Yec8SPN/p32/WB01zfk/I3PcfFPnUOU2CNs0tTyMzYGO8+Q2zF1lrnRQgjgvHcraOO9novK9O9FKmBRzl4L57xQ96Q7xPpjI7DxZ94A5uh5ybqOuvKFGNhcQIhUvM9zqenxM2l8jg0G0paQl30QE4PbbnhZ1cmYYpK9qhJ4BUu+lwdOCiu+OZoW63CXJIe9Ml9o1YKEdU2FIX5ohcl9TAhg7pYoS29U8GCVs=

# command to run tests
script:

  # With flake ignore
  #  E402: <module> level import not at top of file (as per Ansible module developement)
  #  W503: line break before binary operator (PEP8 advices to put logical operator ahead)
  - flake8 plugins/modules/* --max-line-length=160 --ignore=E402,W503

  - bash devops/bin/sanity_test.sh
  - bash devops/bin/gen_doc.sh

# push the generated documentation using GitHub Pages
deploy:
    provider: pages
    strategy: git
    skip_cleanup: true
    token: $GITHUB_API_KEY
    local_dir: docs/build
    keep_history: true
    on:
        branch: dev-collection
