---
- name: "backupios demo"
  hosts: vios
  gather_facts: no

  user: ansible

  collections:
  - ibm.power_vios
  tasks:

  - name: Create an mksysb of the system
    backupios:
      file: /home/padmin/backup.mksysb
      mksysb: yes
      savemedialib: no
